#
# Copyright (c) 2018. Marc Kandel
#

info:
  app:
    name: "Checklists"
    description: "Online shared checkists"
    version: "1.0.0"
management:
  endpoints:
    web:
      exposure:
        include: "*"
#  security:
#    enabled: false
#logging:
#  level:
#    org:
#      hibernate:
#        stat: debug
#        type: trace
server:
  port: 8080

security:
  basic:
    enabled: true
  user:
    name: "admin"
    password: "admin"

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  profiles:
    active: dev
  datasource:
      url: "jdbc:mysql://127.0.0.1:3306/checklists?autoReconnect=true&useSSL=false&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useServerPrepStmts=true&serverTimezone=UTC"
      username: "sa"
      password: "sa"
      driver-class-name: com.mysql.cj.jdbc.Driver
      platform: mysql
  jpa:
    show-sql: false
    properties:
      generate_statistics: false
      hibernate:
        SQL: debug
  jackson:
    serialization:
      indent_output: true
  flyway:
    enabled: true
    core:
      internal:
        command:
          DbMigrate: DEBUG
    check-location: false
    locations: classpath:db/migration
    sqlMigrationPrefix: V
    repeatableSqlMigrationPrefix: R
    ignore-future-migrations: false
    ignore-missing-migrations: false
    table: FlywayMigrationHistory
    baselineOnMigrate: true
